apiVersion: v1
kind: Service
metadata:
  name: frontend-app
  namespace: app
  labels:
    app: frontend-app
spec:
  type: NodePort
  ports:
  - name: http
    port: 8001
    targetPort: http
    nodePort: 32222
    protocol: TCP
  selector:
    app: frontend-app
